#!/usr/bin/env python3
"""Generate src/font_cjk.c + src/font_cjk.h for GarlicMP3.

Rasterizes DroidSansFallbackFull.ttf (Apache-2.0) at 16x16 per CJK glyph so
Japanese song titles render on the RG35XX. Covers everything encodable in
Shift-JIS (full JIS X 0208: kana, kanji, fullwidth punct) + a few JIS X 0213
name kanji (U+9AD9 髙, U+FA11 﨑) so common names don't tofu.

Method: render at 32px, downscale to 16px (preserves Droid's own metrics so
CJK glyph bottoms share one baseline), threshold >127 -> 1-bit rows.

Output tables:
  cjk_cps[]       sorted uint16 codepoints
  cjk_bits[]      32 bytes/glyph = 16 rows x 2 bytes (MSB-left per byte)
  sjis_keys[]     sorted SJIS double-byte codes (for ID3 Shift-JIS decoding)
  sjis_vals[]     matching Unicode codepoints

Run on host (Pillow). Not needed for ARM build - files are committed.
"""
import sys
from PIL import Image, ImageFont, ImageDraw

FONT_PATH = '/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf'
OUT_C = 'src/font_cjk_tables.c'
OUT_H = 'src/font_cjk.h'
SS = 32  # supersample render size
CELL = 16

# JIS X 0213 / common-name additions not in JIS X 0208
EXTRA_CPS = [0x9AD9, 0xFA11, 0x266A, 0x266B, 0x2026, 0x2014, 0x301C, 0xFF5E]


def main():
    font = ImageFont.truetype(FONT_PATH, SS)

    # --- collect codepoints: all shift_jis-encodable (>= 0x80) + extras ---
    cps = set()
    for cp in range(0x80, 0x10000):
        try:
            ch = chr(cp)
            ch.encode('shift_jis')
            cps.add(cp)
        except Exception:
            pass
    for cp in EXTRA_CPS:
        cps.add(cp)
    cps = sorted(cps)
    print('glyph count:', len(cps))

    # --- rasterize each glyph into 16 rows of 2 bytes ---
    bitmaps = []
    missing = []
    for i, cp in enumerate(cps):
        ch = chr(cp)
        img = Image.new('L', (SS, SS), 0)
        d = ImageDraw.Draw(img)
        d.text((0, 0), ch, font=font, fill=255)
        img = img.resize((CELL, CELL), Image.BILINEAR)
        px = img.load()
        rows = []
        any_ink = False
        for yy in range(CELL):
            b0 = b1 = 0
            for xx in range(CELL):
                if px[xx, yy] > 127:
                    if xx < 8:
                        b0 |= 0x80 >> xx
                    else:
                        b1 |= 0x80 >> (xx - 8)
            rows.append((b0, b1))
            if b0 or b1:
                any_ink = True
        if not any_ink:
            missing.append(cp)
        bitmaps.append(rows)
        if i % 1500 == 0:
            print(f'  rasterized {i}/{len(cps)}')
    if missing:
        print('WARN empty glyphs:', [f'U+{cp:04X}' for cp in missing[:30]], f'({len(missing)})')

    # --- SJIS double-byte map (sorted by sjis code) ---
    sjis = set()
    for cp in cps:
        try:
            b = chr(cp).encode('shift_jis')
        except Exception:
            continue
        if len(b) == 2:
            sjis.add(((b[0] << 8) | b[1], cp))
    sjis = sorted(sjis)
    print('sjis pairs:', len(sjis))

    def write_u16(f, values, per_line=12):
        line = []
        for v in values:
            line.append(f'0x{v:04X},')
            if len(line) == per_line:
                f.write('    ' + ' '.join(line) + '\n')
                line = []
        if line:
            f.write('    ' + ' '.join(line) + '\n')

    with open(OUT_C, 'w') as f:
        f.write('/* Auto-generated by tools/gen_cjk_font.py - DO NOT EDIT. */\n')
        f.write('/* Glyphs rasterized from DroidSansFallbackFull.ttf, Apache License 2.0. */\n')
        f.write('#include "font_cjk.h"\n\n')
        f.write(f'const uint16_t cjk_cps[FONT_CJK_MAX] = {{\n')
        write_u16(f, cps)
        f.write('};\n\n')
        f.write('const unsigned char cjk_bits[FONT_CJK_MAX * 32] = {\n')
        for rows in bitmaps:
            vals = []
            for b0, b1 in rows:
                vals.append(f'0x{b0:02X},0x{b1:02X},')
            f.write('    ' + ' '.join(vals) + '\n')
        f.write('};\n\n')
        f.write(f'const uint16_t sjis_keys[FONT_CJK_SJIS_MAX] = {{\n')
        write_u16(f, [s for s, cp in sjis])
        f.write('};\n\n')
        f.write(f'const uint16_t sjis_vals[FONT_CJK_SJIS_MAX] = {{\n')
        write_u16(f, [cp for s, cp in sjis])
        f.write('};\n\n')

    with open(OUT_H, 'w') as f:
        f.write('/* Auto-generated by tools/gen_cjk_font.py - DO NOT EDIT. */\n')
        f.write('#ifndef FONT_CJK_H\n#define FONT_CJK_H\n\n')
        f.write('#include <stdint.h>\n')
        f.write('#include <stddef.h>\n\n')
        f.write(f'#define FONT_CJK_MAX {len(cps)}\n')
        f.write(f'#define FONT_CJK_SJIS_MAX {len(sjis)}\n')
        f.write('extern const uint16_t cjk_cps[FONT_CJK_MAX];\n')
        f.write('extern const unsigned char cjk_bits[FONT_CJK_MAX * 32];\n')
        f.write('extern const uint16_t sjis_keys[FONT_CJK_SJIS_MAX];\n')
        f.write('extern const uint16_t sjis_vals[FONT_CJK_SJIS_MAX];\n\n')
        f.write('/* Lookup helpers implemented in font_cjk.c */\n')
        f.write('int font_cjk_find(uint32_t cp);\n')
        f.write('uint32_t font_cjk_sjis(uint16_t sjis);\n')
        f.write('uint32_t utf8_decode_at(const unsigned char *src, size_t len, size_t *pos);\n')
        f.write('uint32_t utf8_decode(const char **pp);\n')
        f.write('int utf8_encode(uint32_t cp, char *buf);\n')
        f.write('int utf8_from_sjis_or_utf8(const unsigned char *src, size_t src_size, char *out, size_t out_size);\n')
        f.write('int utf8_from_enc0(const unsigned char *src, size_t src_size, char *out, size_t out_size);\n')
        f.write('int utf8_from_utf16(const unsigned char *src, size_t src_size, int big_endian, char *out, size_t out_size);\n\n')
        f.write('#endif\n')


if __name__ == '__main__':
    main()
