/* CJK font lookup + UTF-8/SJIS/UTF-16 helpers for GarlicMP3.
 * Tables generated by tools/gen_cjk_font.py (DroidSansFallbackFull.ttf,
 * Apache-2.0). Lookup via binary search over sorted codepoint keys.
 */
#include "font_cjk.h"

#include <string.h>

int font_cjk_find(uint32_t cp)
{
    int lo = 0;
    int hi = FONT_CJK_MAX - 1;

    if (cp < 0x80) {
        return -1;
    }

    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        if (cjk_cps[mid] == cp) {
            return mid;
        }
        if (cjk_cps[mid] < cp) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return -1;
}

uint32_t font_cjk_sjis(uint16_t sjis)
{
    int lo = 0;
    int hi = FONT_CJK_SJIS_MAX - 1;

    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        if (sjis_keys[mid] == sjis) {
            return sjis_vals[mid];
        }
        if (sjis_keys[mid] < sjis) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return 0;
}

/* --- UTF-8 decoding (bounds-aware) --- */

/* Decode one UTF-8 sequence from src[0..len). On success advances *pos by
 * the sequence length and returns the codepoint. Returns (uint32_t)-1 on
 * invalid/truncated input, consuming at most one byte so callers make
 * progress. */
uint32_t utf8_decode_at(const unsigned char *src, size_t len, size_t *pos)
{
    unsigned char c;
    uint32_t cp;
    size_t need;
    size_t i;

    if (*pos >= len) {
        return 0;
    }
    c = src[*pos];
    if (c < 0x80) {
        *pos += 1;
        return c;
    }
    if (c >= 0xC2 && c <= 0xDF) {
        cp = c & 0x1F;
        need = 1;
    } else if (c >= 0xE0 && c <= 0xEF) {
        cp = c & 0x0F;
        need = 2;
    } else if (c >= 0xF0 && c <= 0xF4) {
        cp = c & 0x07;
        need = 3;
    } else {
        *pos += 1;
        return (uint32_t)-1;
    }
    if (*pos + need >= len) {
        /* not enough continuation bytes */
        *pos += 1;
        return (uint32_t)-1;
    }
    for (i = 1; i <= need; i++) {
        unsigned char t = src[*pos + i];
        if ((t & 0xC0) != 0x80) {
            *pos += 1;
            return (uint32_t)-1;
        }
        cp = (cp << 6) | (t & 0x3F);
    }
    /* Reject overlong/surrogate encodings (leading byte ranges already
     * exclude the worst cases: C0/C1, E0 80-9F, ED A0-BF, F0 80-8F...). */
    if ((c == 0xE0 && (src[*pos + 1] & 0xE0) == 0x80) ||
        (c == 0xED && (src[*pos + 1] & 0xE0) == 0xA0) ||
        (c == 0xF0 && (src[*pos + 1] & 0xF0) == 0x80) ||
        (c == 0xF4 && (src[*pos + 1] & 0xF0) == 0x90)) {
        *pos += 1;
        return (uint32_t)-1;
    }
    *pos += need + 1;
    return cp;
}

/* Convenience wrapper over a NUL-terminated string (bytes). */
uint32_t utf8_decode(const char **pp)
{
    const unsigned char *p = (const unsigned char *)*pp;
    size_t pos = 0;
    size_t len = strlen(*pp);
    uint32_t cp = utf8_decode_at(p, len, &pos);

    *pp += pos;
    return cp;
}

/* Append codepoint as UTF-8 into buf (must hold 4 bytes). Returns bytes. */
int utf8_encode(uint32_t cp, char *buf)
{
    if (cp < 0x80) {
        buf[0] = (char)cp;
        return 1;
    }
    if (cp < 0x800) {
        buf[0] = (char)(0xC0 | (cp >> 6));
        buf[1] = (char)(0x80 | (cp & 0x3F));
        return 2;
    }
    if (cp < 0x10000) {
        buf[0] = (char)(0xE0 | (cp >> 12));
        buf[1] = (char)(0x80 | ((cp >> 6) & 0x3F));
        buf[2] = (char)(0x80 | (cp & 0x3F));
        return 3;
    }
    buf[0] = (char)(0xF0 | (cp >> 18));
    buf[1] = (char)(0x80 | ((cp >> 12) & 0x3F));
    buf[2] = (char)(0x80 | ((cp >> 6) & 0x3F));
    buf[3] = (char)(0x80 | (cp & 0x3F));
    return 4;
}

/* --- Shift-JIS decoding (bounds-aware) --- */

/* Decode one Shift-JIS sequence from src[*pos..len). Single-byte ASCII and
 * half-width katakana 0xA1-0xDF handled; double-byte looked up in the font
 * table. On undefined bytes consumes one byte and returns 0. */
static uint32_t sjis_decode_at(const unsigned char *src, size_t len, size_t *pos)
{
    unsigned char c;
    unsigned char t;
    uint16_t key;
    uint32_t cp;

    if (*pos >= len) {
        return 0;
    }
    c = src[*pos];
    if (c < 0x80) {
        *pos += 1;
        return c;
    }
    if (c >= 0xA1 && c <= 0xDF) {
        *pos += 1;
        return 0xFF61 + (c - 0xA1);
    }
    if (((c >= 0x81 && c <= 0x9F) || (c >= 0xE0 && c <= 0xFC)) && *pos + 1 < len) {
        t = src[*pos + 1];
        if ((t >= 0x40 && t <= 0x7E) || (t >= 0x80 && t <= 0xFC)) {
            key = (uint16_t)((c << 8) | t);
            cp = font_cjk_sjis(key);
            if (cp) {
                *pos += 2;
                return cp;
            }
        }
    }
    *pos += 1;
    return 0;
}

/* Decode ID3v2 encoding-0 / ID3v1 raw bytes (which in the wild are
 * ISO-8859-1, Shift-JIS, or occasionally already UTF-8) into UTF-8.
 * Strategy: pure-ASCII passes through; valid UTF-8 passes through; strict
 * Shift-JIS (every high byte part of a mapped double-byte pair) decodes as
 * SJIS; otherwise bytes are treated as Latin-1 and widened to UTF-8. */
int utf8_from_enc0(const unsigned char *src, size_t src_size,
                   char *out, size_t out_size)
{
    size_t pos = 0;
    size_t j = 0;
    size_t check = 0;
    int valid_utf8 = 1;
    int strict_sjis = 1;
    int saw_high = 0;

    while (check < src_size) {
        uint32_t cp = utf8_decode_at(src, src_size, &check);
        if (cp == (uint32_t)-1) {
            valid_utf8 = 0;
            break;
        }
    }

    if (valid_utf8) {
        while (pos < src_size && j + 4 < out_size) {
            uint32_t cp = utf8_decode_at(src, src_size, &pos);
            if (cp == (uint32_t)-1) {
                continue;
            }
            if (cp < 32 || cp == 127) {
                continue;
            }
            j += utf8_encode(cp, out + j);
        }
        out[j] = '\0';
        return (int)j;
    }

    /* Strict Shift-JIS validation. */
    {
        size_t p = 0;
        while (p < src_size) {
            unsigned char c = src[p];
            unsigned char t;
            uint16_t key;
            if (c < 0x80) {
                p++;
                continue;
            }
            saw_high = 1;
            if (((c >= 0x81 && c <= 0x9F) || (c >= 0xE0 && c <= 0xFC)) && p + 1 < src_size) {
                t = src[p + 1];
                if ((t >= 0x40 && t <= 0x7E) || (t >= 0x80 && t <= 0xFC)) {
                    key = (uint16_t)((c << 8) | t);
                    if (font_cjk_sjis(key)) {
                        p += 2;
                        continue;
                    }
                }
            }
            strict_sjis = 0;
            break;
        }
    }

    if (strict_sjis && saw_high) {
        while (pos < src_size && j + 4 < out_size) {
            uint32_t cp = sjis_decode_at(src, src_size, &pos);
            if (cp == 0) {
                continue;
            }
            if (cp < 32 || cp == 127) {
                continue;
            }
            j += utf8_encode(cp, out + j);
        }
        out[j] = '\0';
        return (int)j;
    }

    /* Latin-1 fallback: each byte >= 0x80 is one codepoint U+0080..U+00FF. */
    while (pos < src_size && j + 4 < out_size) {
        unsigned char c = src[pos++];
        if (c < 32 || c == 127) {
            continue;
        }
        if (c < 0x80) {
            j += utf8_encode(c, out + j);
        } else {
            /* C1 controls 0x80-0x9F are dropped; visible Latin-1 kept. */
            if (c < 0xA0) {
                continue;
            }
            j += utf8_encode(c, out + j);
        }
    }
    out[j] = '\0';
    return (int)j;
}

/* Decode a raw byte buffer that may be UTF-8 or Shift-JIS into a UTF-8
 * string. Valid-UTF-8 content is passed through; otherwise Shift-JIS is
 * assumed. Returns bytes written (excluding NUL). */
int utf8_from_sjis_or_utf8(const unsigned char *src, size_t src_size,
                           char *out, size_t out_size)
{
    size_t pos = 0;
    size_t j = 0;
    int valid_utf8 = 1;
    size_t check = 0;

    while (check < src_size) {
        uint32_t cp = utf8_decode_at(src, src_size, &check);
        if (cp == (uint32_t)-1) {
            valid_utf8 = 0;
            break;
        }
    }

    if (valid_utf8) {
        while (pos < src_size && j + 4 < out_size) {
            uint32_t cp = utf8_decode_at(src, src_size, &pos);
            if (cp == (uint32_t)-1) {
                continue; /* pos already advanced by 1 */
            }
            if (cp < 32 || cp == 127) {
                continue;
            }
            j += utf8_encode(cp, out + j);
        }
        out[j] = '\0';
        return (int)j;
    }

    while (pos < src_size && j + 4 < out_size) {
        uint32_t cp = sjis_decode_at(src, src_size, &pos);
        if (cp == 0) {
            continue;
        }
        if (cp < 32 || cp == 127) {
            continue;
        }
        j += utf8_encode(cp, out + j);
    }
    out[j] = '\0';
    return (int)j;
}

/* Decode UTF-16 (BOM-aware; big_endian is the fallback when no BOM) to
 * UTF-8. Returns bytes written (excluding NUL). */
int utf8_from_utf16(const unsigned char *src, size_t src_size, int big_endian,
                    char *out, size_t out_size)
{
    size_t pos = 0;
    size_t j = 0;
    int le = !big_endian;

    if (src_size >= 2) {
        if (src[0] == 0xFF && src[1] == 0xFE) {
            le = 1;
            pos = 2;
        } else if (src[0] == 0xFE && src[1] == 0xFF) {
            le = 0;
            pos = 2;
        }
    }

    while (pos + 1 < src_size && j + 4 < out_size) {
        uint16_t u;
        uint32_t cp;
        u = (uint16_t)(le ? (src[pos] | (src[pos + 1] << 8))
                          : ((src[pos] << 8) | src[pos + 1]));
        pos += 2;
        cp = u;
        if (u >= 0xD800 && u <= 0xDBFF && pos + 1 < src_size) {
            uint16_t lo = (uint16_t)(le ? (src[pos] | (src[pos + 1] << 8))
                                        : ((src[pos] << 8) | src[pos + 1]));
            if (lo >= 0xDC00 && lo <= 0xDFFF) {
                cp = 0x10000 + (((uint32_t)(u - 0xD800)) << 10) + (lo - 0xDC00);
                pos += 2;
            }
        }
        if (cp < 32 || cp == 127) {
            continue;
        }
        j += utf8_encode(cp, out + j);
    }
    out[j] = '\0';
    return (int)j;
}
