/* Auto-generated by tools/gen_cjk_font.py - DO NOT EDIT. */
#ifndef FONT_CJK_H
#define FONT_CJK_H

#include <stdint.h>
#include <stddef.h>

#define FONT_CJK_MAX 6949
#define FONT_CJK_SJIS_MAX 6879
extern const uint16_t cjk_cps[FONT_CJK_MAX];
extern const unsigned char cjk_bits[FONT_CJK_MAX * 32];
extern const uint16_t sjis_keys[FONT_CJK_SJIS_MAX];
extern const uint16_t sjis_vals[FONT_CJK_SJIS_MAX];

/* Lookup helpers implemented in font_cjk.c */
int font_cjk_find(uint32_t cp);
uint32_t font_cjk_sjis(uint16_t sjis);
uint32_t utf8_decode_at(const unsigned char *src, size_t len, size_t *pos);
uint32_t utf8_decode(const char **pp);
int utf8_encode(uint32_t cp, char *buf);
int utf8_from_sjis_or_utf8(const unsigned char *src, size_t src_size, char *out, size_t out_size);
int utf8_from_enc0(const unsigned char *src, size_t src_size, char *out, size_t out_size);
int utf8_from_utf16(const unsigned char *src, size_t src_size, int big_endian, char *out, size_t out_size);

#endif
